package np.santa

/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class ChristmasShopMainTest extends FunSuite {
  test("someLibraryMethod is always true") {

  }
}
